# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Node.js as the base image
FROM node:20-alpine

# Install pnpm
RUN npm install -g pnpm

# Set the working directory
WORKDIR /app

# Copy the package.json and pnpm-lock.yaml (if available) first
COPY package.json ./

# Install dependencies
RUN pnpm install

# Copy the rest of the application
COPY . .

# Set environment variables for the application
# Assuming an API key is needed as per README
ENV E2B_API_KEY=your_api_key_here

# Default command to run the server
CMD ["node", "src/index.js"]
